//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.file` struct is generated, and contains static references to 2 files.
  struct file {
    /// Resource file `configuration.json`.
    static let configurationJson = Rswift.FileResource(bundle: R.hostingBundle, name: "configuration", pathExtension: "json")
    /// Resource file `logo.json`.
    static let logoJson = Rswift.FileResource(bundle: R.hostingBundle, name: "logo", pathExtension: "json")

    /// `bundle.url(forResource: "configuration", withExtension: "json")`
    static func configurationJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.configurationJson
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "logo", withExtension: "json")`
    static func logoJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.logoJson
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 1 images.
  struct image {
    /// Image `logo_is`.
    static let logo_is = Rswift.ImageResource(bundle: R.hostingBundle, name: "logo_is")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "logo_is", bundle: ..., traitCollection: ...)`
    static func logo_is(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.logo_is, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    struct uiApplicationSceneManifest {
      static let _key = "UIApplicationSceneManifest"
      static let uiApplicationSupportsMultipleScenes = false

      struct uiSceneConfigurations {
        static let _key = "UISceneConfigurations"

        struct uiWindowSceneSessionRoleApplication {
          struct defaultConfiguration {
            static let _key = "Default Configuration"
            static let uiSceneClassName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneClassName") ?? "UIWindowScene"
            static let uiSceneConfigurationName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneConfigurationName") ?? "Default Configuration"
            static let uiSceneDelegateClassName = infoPlistString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication", "Default Configuration"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate"

            fileprivate init() {}
          }

          fileprivate init() {}
        }

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.nib` struct is generated, and contains static references to 4 nibs.
  struct nib {
    /// Nib `FeedsCell`.
    static let feedsCell = _R.nib._FeedsCell()
    /// Nib `FeedsViewController`.
    static let feedsViewController = _R.nib._FeedsViewController()
    /// Nib `IntroductionViewController`.
    static let introductionViewController = _R.nib._IntroductionViewController()
    /// Nib `PostViewController`.
    static let postViewController = _R.nib._PostViewController()

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "FeedsCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.feedsCell) instead")
    static func feedsCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.feedsCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "FeedsViewController", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.feedsViewController) instead")
    static func feedsViewController(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.feedsViewController)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "IntroductionViewController", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.introductionViewController) instead")
    static func introductionViewController(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.introductionViewController)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "PostViewController", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.postViewController) instead")
    static func postViewController(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.postViewController)
    }
    #endif

    static func feedsCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> FeedsCell? {
      return R.nib.feedsCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? FeedsCell
    }

    static func feedsViewController(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.feedsViewController.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    static func introductionViewController(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> IntroductionView? {
      return R.nib.introductionViewController.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? IntroductionView
    }

    static func postViewController(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> PostView? {
      return R.nib.postViewController.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? PostView
    }

    fileprivate init() {}
  }

  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `FeedsCell`.
    static let feedsCell: Rswift.ReuseIdentifier<FeedsCell> = Rswift.ReuseIdentifier(identifier: "FeedsCell")

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 1 localization keys.
    struct localizable {
      /// Value: Start
      static let introductionViewControllerContinueButton = Rswift.StringResource(key: "IntroductionViewController.continue.button", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: Start
      static func introductionViewControllerContinueButton(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("IntroductionViewController.continue.button", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "IntroductionViewController.continue.button"
        }

        return NSLocalizedString("IntroductionViewController.continue.button", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct nib {
    struct _FeedsCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = FeedsCell

      let bundle = R.hostingBundle
      let identifier = "FeedsCell"
      let name = "FeedsCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> FeedsCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? FeedsCell
      }

      fileprivate init() {}
    }

    struct _FeedsViewController: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "FeedsViewController"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      fileprivate init() {}
    }

    struct _IntroductionViewController: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "IntroductionViewController"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> IntroductionView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? IntroductionView
      }

      fileprivate init() {}
    }

    struct _PostViewController: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "PostViewController"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> PostView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? PostView
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }
  #endif

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
